# fly.toml app configuration file generated for wispy-wildflower-8862 on 2023-05-30T11:01:55-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-wildflower-8862"
primary_region = "lax"
